global:
  scrape_interval: 60s
  evaluation_interval: 60s
  external_labels:
    monitor: "oracle_OPERATOR_PLACEHOLDER"

remote_write:
  - url: https://URL_PLACEHOLDER.grafana.net/api/prom/push
    basic_auth:
      username: USERNAME_PLACEHOLDER
      password: PASSWORD_PLACEHOLDER
    write_relabel_configs:
    - source_labels: [__name__]
      regex: '^oracle.*'
      action: keep

scrape_configs:
  - job_name: "geth"
    static_configs:
    - targets: ["geth:6060"]
    metrics_path: /debug/metrics/prometheus
  - job_name: "teku"
    static_configs:
    - targets: ["teku:8008"]
  - job_name: "oracle"
    static_configs:
    - targets: ["oracle:8008"]